Add more examples to README.md
pekat-vision/pekat-vision-sdk-python pull request #28
Opened 2024-09-09 12:00 UTC by Adamasterr

2024-09-09 13:05 UTC, KristynaJanku requested changes

2024-09-09 13:05 UTC, KristynaJanku commented on README.md
>  flow_result = result.context["result"]
This gives just the boolean evaluation result, not some data structure, no?
```suggestion
# Get the evaluation result (True/False)

flow_result = result.context["result"]
```

2024-09-10 10:07 UTC, xvalec01 approved these changes

2024-09-10 10:07 UTC, xvalec01 commented on README.md
> +p_local = Instance("~/PekatVisionProjects/my_project", port=8100, host="0.0.0.0")
```suggestion
# Start a project locally (host 0.0.0.0 - listen on all interfaces)

p_local = Instance("~/PekatVisionProjects/my_project", port=8100, host="0.0.0.0")
```
I would add this to people who would copy this line without any knowledge what 0.0.0.0 means even that it is stated in the class docstring.

2024-09-10 10:48 UTC, KristynaJanku approved these changes

2024-09-10 11:41 UTC, merged